name: mon_app_mob
description: Une application mobile en Flutter
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_lints: ^5.0.0 # Mise à jour pour éviter les erreurs
  flutter_web_auth_2: 3.1.2
  appwrite: ^15.0.2
  js: ^0.6.4
  device_info_plus: 10.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
